# Project: EventHub
# Override framework defaults here

BROWSER = chrome
HEADLESS = true

EXPLICIT_WAIT_TIMEOUT = 10
HARD_WAIT_TIMEOUT = 2
STEP_TIME = 1
PAGE_LOAD_TIMEOUT = 60
API_TIMEOUT = 20

# Change TEST_SUITE to show the title in email
TEST_SUITE = SIT Suite
RETRY_TEST_FAIL = 2
OVERRIDE_REPORTS = yes
