# Environment: Development
BASE_URL=https://eventhub.rahulshettyacademy.com/login
API_BASE_URL=https://api.eventhub.rahulshettyacademy.com/api

# Auth credentials for dev
VALID_LOGIN_EMAIL = claude.walter@yahoo.com
VALID_LOGIN_PASSWORD = Mo0^f1ZG
