# Production Environment
ENV=PRODUCTION

# URLs
BASE_URL=https://eventhub.rahulshettyacademy.com/login
API_BASE_URL=https://api.eventhub.rahulshettyacademy.com/api

# Test Credentials
VALID_LOGIN_EMAIL=claud.kohler@gmail.com
VALID_LOGIN_PASSWORD=Ys6^PCdF
