# UAT Environment
ENV=UAT

# URLs
BASE_URL=https://eventhub.rahulshettyacademy.com/login
API_BASE_URL=https://api.eventhub.rahulshettyacademy.com/api

# Test Credentials
VALID_LOGIN_EMAIL=alline.mayer@hotmail.com
VALID_LOGIN_PASSWORD=Yy0*P1t%
