# Login Page
LOGIN_PAGE_LABEL = //h1[normalize-space()='Sign in to EventHub']
EMAIL = //input[@id='email']
PASSWORD = //input[@id='password']
SIGN_IN_BUTTON = //button[@id='login-btn']
SUCCESS_LOGIN_LABEL = //span[@id='user-email-display']
LOG_OUT_BUTTON = //button[@id='logout-btn']
ERROR_TOAST_MESSAGE = (//p[@class='text-sm font-medium flex-1 leading-snug'])[1]

# Register Page
NAVIGATE_TO_REGISTER_PAGE = //a[normalize-space()='Register']
REGISTER_PAGE_LABEL = //h1[normalize-space()='Create your account']
REGISTER_EMAIL = //input[@id='register-email']
REGISTER_PASSWORD = //input[@id='register-password']
REGISTER_CONF_PASSWORD = //input[@placeholder='Repeat your password']
CREATE_ACCOUNT_BUTTON = //button[@id='register-btn']

# Event Page
NAVIGATE_TO_EVENT_PAGE = //a[@id='nav-events']
EVENT_PAGE_LABEL = //h1[normalize-space()='Upcoming Events']
EVENT_LIST = article#event-card
SEARCH_EVENT_INPUT = //input[contains(@placeholder,'Search events')]
SELECT_EVENT_CATEGORY = body > main:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > select:nth-child(1)
SELECT_EVENT_CITY = body > main:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > select:nth-child(1)
CLEAR_FILTER = //button[normalize-space()='Clear filters']
ADD_NEW_EVENT = //button[normalize-space()='Add New Event']
CREATE_EVENT_PAGE = //h2[normalize-space()='+ New Event']
EVENT_TITLE = //input[@id='event-title-input']
EVENT_DESCRIPTION = //textarea
EVENT_CATEGORY = //select[@id='category']
EVENT_CITY = //input[@id='city']
EVENT_VENUE = //input[@id='venue']
EVENT_DATE = //input[@id='event-date-&-time']
EVENT_PRICE = //input[@id='price-($)']
EVENT_SEAT = //input[@id='total-seats']
EVENT_IMAGE_URL = //input[@id='image-url-(optional)']
ADD_EVENT_BUTTON = //button[@id='add-event-btn']
NO_EVENT_FOUND_MESSAGE = //h3[normalize-space()='No events found']

BOOK_NOW_BUTTON = .//a[normalize-space()='Book Now']
EVENT_INFORMATION_DETAIL = div[class='grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6']
ABOUT_EVENT_DETAIL = //p[@class='text-gray-600 leading-relaxed whitespace-pre-wrap']

# My Bookings Page
NAVIGATE_TO_MY_BOOKING_PAGE = //a[@id='nav-bookings']
MY_BOOKING_PAGE_LABEL = //h1[normalize-space()='My Bookings']
EMPTY_STATE_LABEL = //h3[normalize-space()='No bookings yet']
CURRENT_TICKET_QTY = //span[@id='ticket-count']
ADD_TICKET = //button[normalize-space()='+']
MIN_TICKET = //button[contains(text(),'−')]
CUSTOMER_NAME = //input[@id='customerName']
CUSTOMER_EMAIL = //input[@id='customer-email']
CUSTOMER_PHONE = //input[@id='phone']
CONFIRM_BOOKING_BUTTON = //button[@id='confirm-booking']
ACTUAL_TOTAL_PRICE = .text-lg.font-bold.text-indigo-700
SUCCESS_BOOKING_LABEL = //p[@class='text-gray-500 text-sm mb-5']
VIEW_MY_BOOKINGS = //button[normalize-space()='View My Bookings']
LIST_OF_BOOKED_EVENT = #booking-card
VIEW_DETAILS_BUTTON = //button[normalize-space()='View Details']
DELETE_BOOKING_BUTTON = //button[normalize-space()='Clear all bookings']
CANCEL_BOOKING_BUTTON = //button[@id='cancel-booking-btn']
CANCEL_CONFIRM_BUTTON = //button[@id='confirm-dialog-yes']
REFUND_SECTION = //*[normalize-space()='Refund']
CHECK_ELIGIBLE_OR_NO_ELIGIBLE_BUTTON = //button[@id='check-refund-btn']
